---
- name: Zálohování osobních dat uživatelů
  hosts: '{{ seznam_stanic }}'
  tasks:
   - name: Zjistí seznam podsložek složky
     win_find: 
      paths: '{{ cesta_slozky }}'
      file_type: directory
     register: seznam_slozek
     
   - name: Vytvoří složku, pokud je potřeba
     win_file: 
      path: "C:\\Users\\test\\{{ item | win_dirname }}\\Documents"
     with_items: "{{ seznam_slozek.files }}"
      
   - name: Synchronizace
     win_robocopy: 
      src: "C:\\Users\\{{ item | win_dirname }}\\Documents"
      dest: "C:\\Users\\test\\{{ item | win_dirname }}\\Documents"
      recurse: True
     with_items: "{{ seznam_slozek.files }}"
       
