---
- name: Zálohování osobních dat uživatelů
  hosts: '{{ seznam_stanic }}'
  tasks:
   - name: Synchronizae dvou složek
      win_robocopy: 
       src: C:\Users\david.chlup\Documents
       dest: X:\Backup
       recurse: yes
       
