---
- name: Zálohování osobních dat uživatelů
  hosts: '{{ seznam_stanic }}'
  tasks:
   - name: Zjistí seznam podsložek složky
     win_find: 
      paths: '{{ cesta_slozky }}'
     register: seznam_slozek
   - name: Synchronizace
     win_robocopy: 
      src: "C:\\Users\\{{ item }}"
      dest: "C:\\Users\\test\\{{ item }}"
      recurse: True
     with_items: "{{ seznam_slozek }}"
       
