---
- name: Zálohování osobních dat uživatelů
  hosts: '{{ seznam_stanic }}'
  tasks:
   - name: Synchronizae dvou složek
     win_robocopy: 
      src: '{{ slozka_zdroj }}'
      dest: '{{ slozka_cil }}'
      recurse: yes
       
